sudo: false
language: node_js
node_js:
- 8
script:
- npm test
after_success:
- npm run report-coverage
env:
  matrix:
    secure: OLYVg+/5SEMI1mqfW40htQBwNOJYaBQ4o9OnVQGMP/wtUBLK7D+hw8YJAzhiEKOMZ+RMOBMpuKx3771d48DLvQiNfXw/tjGw9fhEh2zzCg9BCd0VwspbOSj4PMAntSN/2OqnB6BjzyW8AbW+lh43IlrxlkHgNRNuwJ/KMUIDwiuvC0TLrP5ISahdpAD5rqKyFrx/Fs/o4z2M7lpH1Dl/0iO/lY9yMbrO5xMtTy31tG7Q6jU5pJnqxIrAIyZUx3dEO59n0RxiB8tQU6Tnkuse29mOauN5ImsxNi8uMy1De30ZSSxhZ3aZoydiiZL2cV0Rb/pIBHN3Z+KV3J8FVjPCV0CqdbLgVsH8lw3Ycv3M4jY91FDqfQ4eyLtxvk9d9bojFtdppWs90Y3elgFeqzchMtDCL+pcnK3Y3SAJxGQu52dAnlqJNtzHfqBGwzbfmttXh6VrFTuxPmqPzNwgYJUyT0GUN4KbH315A7LvvewBeanelT1MUschQlEsartPRjm/gijqnlqZ/rRriUvDnG7luBOlwA8hVYtU5jYxORxGxVgE2UDsNh3xsBcLZ+PQEhjZKFCrr3sHIgXMv0juTxCGyVX4A9SH3OAPV2g0IFtHyjK1YwVtIMuWJJerN92NuUpt10KHg+jnKfoTg/1HoixMUJytqBgLYYaUgIpuStWfDMY=
